# Generated by Django 2.0.2 on 2019-10-28 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='登录', help_text='登录', max_length=100, null=True, verbose_name='操作类型')),
                ('action_time', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='操作时间', max_length=100, null=True, verbose_name='操作时间')),
            ],
        ),
        migrations.CreateModel(
            name='OperationLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='successful', help_text='类型', max_length=100, null=True, verbose_name='类型')),
                ('content', models.CharField(blank=True, default='无修改', help_text='修改详情', max_length=100, null=True, verbose_name='修改详情')),
                ('action_time', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='操作时间', null=True, verbose_name='操作时间')),
            ],
        ),
        migrations.CreateModel(
            name='ProList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_title', models.TextField(blank=True, default=0, help_text='问题标题', max_length=100, null=True, verbose_name='问题标题')),
                ('pro_brief', models.TextField(help_text='问题简短描述', max_length=100, verbose_name='回答简短描述')),
                ('pro_desc', models.TextField(default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '问题列表',
                'verbose_name_plural': '问题列表',
            },
        ),
    ]
